//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class TaichoColors
{
	public static Color PLAYERONE_LVL1 = new Color(0.968F,0.835F,0.219F,1F);
	public static Color PLAYERONE_LVL2 = new Color(0.749F,0.635F,0.18F,1F);
	public static Color PLAYERONE_LVL3 = new Color(0.467F,0.408F,0.114F,1F);
	public static Color PLAYERONE_TAICHO = new Color(0.1F,0.1F,0.1F,1F); //TODO
	


	public TaichoColors ()
	{
	}
}

