//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class TaichoColors
{
	public static Color PLAYERONE_LVL1 = new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_LVL2 = new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_LVL3 = new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_TAICHO = new Color(0.412F,0.647F,0.514F); //TODO
	public static Color PLAYERTWO_LVL1 = new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_LVL2 = new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_LVL3 = new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_TAICHO = new Color(0.925F,0.475F,0.604F,1F); //TODO


	public TaichoColors ()
	{
	}
}

