
using System;
using UnityEngine;
public class TaichoColors
{
	//color scheme generated here
	//http://paletton.com/palette.php?uid=7000H0kllllaFw0g0qFqFg0w0aF

	public static Color PLAYERONE_LVL1 = HexToColor ("80A4A2");//new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_LVL2 = HexToColor ("80A4A2");//new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_LVL3 = HexToColor ("80A4A2");//new Color(0.302F,0.537F,0.388F,1F);
	public static Color PLAYERONE_TAICHO = HexToColor ("80A4A2");//new Color(0.412F,0.647F,0.514F);
	public static Color PLAYERTWO_LVL1 = HexToColor ("DD765D");//new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_LVL2 = HexToColor ("DD765D");//new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_LVL3 = HexToColor ("DD765D");//new Color(0.624F,0.008F,0.318F,1F);
	public static Color PLAYERTWO_TAICHO = HexToColor ("DD765D");//new Color(0.925F,0.475F,0.604F,1F);

	public static Color TILE_SELECT_PLAYERONE = HexToColor ("E79C64");
	public static Color TILE_SELECT_PLAYERTWO = HexToColor ("82B08B");
	public static Color MOVE_MOVE = HexToColor ("2F3944");
//	public static Color MOVE_MOVE = HexToColor ("004400");
//	public static Color MOVE_ATTACK = HexToColor ("AA3939");
	public static Color MOVE_ATTACK = HexToColor ("CF5060");
	public static Color TILE_STACK_PLAYERONE = HexToColor ("9AC76E");
	public static Color TILE_STACK_PLAYERTWO = HexToColor ("9AC76E");

	public static Color TAICHO_LOGO_TEXT = HexToColor ("CF5060");
//	public static Color TAICHO_LOGO_BACKGROUND = HexToColor ("64B058");
	public static Color TAICHO_MENU_BUTTONS = HexToColor ("80A4A2");

	public static Color TAICHO_BOARD_TILE_TINT = HexToColor ("E2BA87");//D2AC68");
	public static Color TAICHO_BOARD_CASTLE_TINT = HexToColor ("D2AC68");//DD765D");


	public TaichoColors ()
	{
	}

	private static string ColorToHex(Color32 color) {
		string hex = color.r.ToString("X2") + color.g.ToString("X2") + color.b.ToString("X2");
		return hex;
	}
	
	private static Color HexToColor(string hex) {
		byte r = byte.Parse(hex.Substring(0,2), System.Globalization.NumberStyles.HexNumber);
		byte g = byte.Parse(hex.Substring(2,2), System.Globalization.NumberStyles.HexNumber);
		byte b = byte.Parse(hex.Substring(4,2), System.Globalization.NumberStyles.HexNumber);
		return new Color32(r,g,b, 255);
	}

	/**
	 * 
	 * 
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=c5A2M0B3A0kllllaFw0g0qFqFg0w0aF


*** Primary color:

   shade 0 = #A6373F = rgb(166, 55, 63) = rgba(166, 55, 63,1) = rgb0(0.651,0.216,0.247)
   shade 1 = #F8A6AC = rgb(248,166,172) = rgba(248,166,172,1) = rgb0(0.973,0.651,0.675)
   shade 2 = #CF676F = rgb(207,103,111) = rgba(207,103,111,1) = rgb0(0.812,0.404,0.435)
   shade 3 = #7C151C = rgb(124, 21, 28) = rgba(124, 21, 28,1) = rgb0(0.486,0.082,0.11)
   shade 4 = #530006 = rgb( 83,  0,  6) = rgba( 83,  0,  6,1) = rgb0(0.325,0,0.024)

*** Secondary color (1):

   shade 0 = #AA7439 = rgb(170,116, 57) = rgba(170,116, 57,1) = rgb0(0.667,0.455,0.224)
   shade 1 = #FFD6AA = rgb(255,214,170) = rgba(255,214,170,1) = rgb0(1,0.839,0.667)
   shade 2 = #D4A26A = rgb(212,162,106) = rgba(212,162,106,1) = rgb0(0.831,0.635,0.416)
   shade 3 = #804D15 = rgb(128, 77, 21) = rgba(128, 77, 21,1) = rgb0(0.502,0.302,0.082)
   shade 4 = #552C00 = rgb( 85, 44,  0) = rgba( 85, 44,  0,1) = rgb0(0.333,0.173,0)

*** Secondary color (2):

   shade 0 = #2B4C6F = rgb( 43, 76,111) = rgba( 43, 76,111,1) = rgb0(0.169,0.298,0.435)
   shade 1 = #738CA6 = rgb(115,140,166) = rgba(115,140,166,1) = rgb0(0.451,0.549,0.651)
   shade 2 = #4A6A8A = rgb( 74,106,138) = rgba( 74,106,138,1) = rgb0(0.29,0.416,0.541)
   shade 3 = #133253 = rgb( 19, 50, 83) = rgba( 19, 50, 83,1) = rgb0(0.075,0.196,0.325)
   shade 4 = #041D37 = rgb(  4, 29, 55) = rgba(  4, 29, 55,1) = rgb0(0.016,0.114,0.216)

*** Complement color:

   shade 0 = #3C8D2F = rgb( 60,141, 47) = rgba( 60,141, 47,1) = rgb0(0.235,0.553,0.184)
   shade 1 = #96D38D = rgb(150,211,141) = rgba(150,211,141,1) = rgb0(0.588,0.827,0.553)
   shade 2 = #64B058 = rgb(100,176, 88) = rgba(100,176, 88,1) = rgb0(0.392,0.69,0.345)
   shade 3 = #1E6912 = rgb( 30,105, 18) = rgba( 30,105, 18,1) = rgb0(0.118,0.412,0.071)
   shade 4 = #0A4600 = rgb( 10, 70,  0) = rgba( 10, 70,  0,1) = rgb0(0.039,0.275,0)


#####  Generated by Paletton.com (c) 2002-2014
	 * 
	 **/
}

