//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class MoveClass
{
	private int value;
	public MoveClass (int val)
	{
		this.value = val;
	}
	public int getValue () {
		return this.value;
	}
}

