//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using System.Collections.Generic;
using com.cosmichorizons.enums;
using com.cosmichorizons.basecomponents;
using com.cosmichorizons.interfaces;
public class SurroundingBoardComponentMovesClass: LegalMoves
{	
	public override MoveClass[] getMoves () {
		MoveClass[] moves = new MoveClass[8];
		moves [0] = new MoveClass (1);
		moves [1] = new MoveClass (10);
		moves [2] = new MoveClass (8);
		moves [3] = new MoveClass (9);
		moves [4] = new MoveClass (-1);
		moves [5] = new MoveClass (-10);
		moves [6] = new MoveClass (-8);
		moves [7] = new MoveClass (-9);
		return moves;
	}

	public override int getMove (int i) {
		return getMoves ()[i].getValue ();
	}
	
	public override int getBufferValue ()
	{
		return -1;
	}
	
	/**
	 */
	public override List<List<MoveClass>> getBlockablePathsOfMoves () {
		return new List<List<MoveClass>>();
	}
}

