//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using com.cosmichorizons.basecomponents;

public abstract class AbstractPanel {
	public AbstractPanel ()	{
	}

	public abstract String getHeaderText ();
	public abstract String getTutorialText ();
	public abstract void processGameGrid (TaichoGameGrid grid);

	protected static void populateTileWithCharacter (TaichoGameGrid grid, BoardComponent tempBc) {
		populateTileWithCharacter (grid, tempBc, true);
	}
	protected static void populateTileWithCharacter (TaichoGameGrid grid, BoardComponent tempBc, bool isSelected) {
		for (int i = 0; i < grid.validMoves.Count; i++) {
			Tile previousValidTile = grid.getTileForBoardComponent( grid.validMoves[i] );
			previousValidTile.disableHighlighter();
		}
		grid.validMoves.Clear ();
		Tile tile = grid.getTileForBoardComponent (tempBc);
		tile.boardComponent = tempBc;
		if (isSelected) tile.boardComponent.Selected = true;
		grid.taicho.board [tempBc.Coordinate.PosY, tempBc.Coordinate.PosX] = tile.boardComponent;
		tile.enableSprite ();
		if (isSelected) {
			grid.selectedTile = tile;
			grid.validMoves = tile.boardComponent.Character.getPossibleMoves (grid.taicho, tile.boardComponent);
			grid.highlightPossibleMovesForSelectedComponent ();
		}
		tile.updateSprite ();
	}
}

