//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using com.cosmichorizons.basecomponents;

public class PanelUtils {
	public PanelUtils () {
	}

	public static void populateTileWithCharacter (TaichoGameGrid grid, BoardComponent tempBc) {
		Tile tile = grid.getTileForBoardComponent (tempBc);
		tile.boardComponent.removeCharacter ();
		tile.boardComponent = tempBc;
		tile.boardComponent.Selected = true;
		grid.taicho.board [tempBc.Coordinate.PosY, tempBc.Coordinate.PosX] = tile.boardComponent;
		tile.enableSprite ();
		grid.selectedTile = tile;
		grid.validMoves = tile.boardComponent.Character.getPossibleMoves(grid.taicho, tile.boardComponent);
		grid.highlightPossibleMovesForSelectedComponent ();
		tile.updateSprite ();
	}
}

